# Generated by Django 5.2.3 on 2025-11-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_comments_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='restaurant',
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(verbose_name='Година та день бронювання столика'),
        ),
    ]
