# Generated by Django 5.2.3 on 2025-11-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_comments_restaurant_alter_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='role',
            field=models.CharField(choices=[('admin', 'Адміністрато'), ('bartender', 'Бармен'), ('waiter', 'Офіціант')], default='waiter', max_length=100),
        ),
    ]
