# Generated by Django 5.2.3 on 2025-11-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_menu_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('breakfast', 'Сніданок'), ('lunch', 'Обід'), ('dinner', 'Вечеря')], default='lunch', max_length=100)),
                ('type', models.CharField(choices=[('burgers', 'Бургери'), ('salads', 'Салати'), ('soups', 'Супи'), ('main_dishes', 'Основні страви'), ('pizza', 'Піца'), ('pasta', 'Паста'), ('cold_appetizers', 'Холодні закуски'), ('hot_appetizers', 'Гарячі закуски'), ('desserts', 'Десерти'), ('drinks', 'Напої')], default='main_dishes', max_length=100)),
                ('customer', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=25, unique=True)),
                ('street', models.CharField(max_length=100)),
                ('pay', models.CharField(choices=[('online', 'Онлайн'), ('upon receipt', 'При отримані')], default='online', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='workers',
            name='photo',
            field=models.ImageField(blank=True, upload_to='workers/'),
        ),
    ]
