# Generated by Django 5.2.3 on 2025-11-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_menuorder_alter_workers_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='photo',
            field=models.ImageField(blank=True, upload_to='menu/'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='data_came_work',
            field=models.DateField(auto_now_add=True),
        ),
    ]
