# Generated by Django 5.2.3 on 2025-11-14 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_special_alter_menu_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='special',
            name='text',
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_user', to='main.menu'),
        ),
        migrations.AddField(
            model_name='special',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.menu'),
        ),
        migrations.AddField(
            model_name='special',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
