# Generated by Django 5.2.3 on 2025-11-25 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_special_text_customuser_favorite_special_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuorder',
            name='menu_items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.menu'),
        ),
    ]
