# Generated by Django 5.2.3 on 2025-11-25 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_menuorder_menu_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='guests_count',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Кількість гостей'),
        ),
    ]
