# Generated by Django 5.2.3 on 2025-12-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_menuorder_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='type',
            new_name='type2',
        ),
        migrations.AddField(
            model_name='menu',
            name='type1',
            field=models.CharField(choices=[('breakfast', 'Сніданок'), ('lunch', 'Обід'), ('dinner', 'Вечеря')], default='lunch', max_length=100),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
