# Generated by Django 5.2.3 on 2025-12-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_type_menu_type2_menu_type1_alter_menu_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuorder',
            old_name='type',
            new_name='type2',
        ),
        migrations.AddField(
            model_name='menuorder',
            name='type1',
            field=models.CharField(choices=[('breakfast', 'Сніданок'), ('lunch', 'Обід'), ('dinner', 'Вечеря')], default='lunch', max_length=100),
        ),
        migrations.AlterField(
            model_name='menuorder',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
